[workspace]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "hephaestus"
platforms = ["linux-64"]
version = "0.1.0"

[dependencies]
mojo = "<1.0.0"
max = ">=26.3.0"
python = ">=3.12,<3.13"
